### ISSUE TITLE
eventbrite shows a google map

### ISSUE THREAD

**Issue by harry-wood** [OSMLatam/sotm-2016#10]
https://www.eventbrite.com/e/state-of-the-map-latam-2016-tickets-27254747684

Annoyingly eventbrite likes to show google maps. The only fix I know for this, is to use the eventbrite option to disable the map, and then you can add your own map as a static image in the HTML description

**Comment by willemarcel** [comment]
Thanks, Harry! I updated the page with a OSM map image!
